package one.chartsy.charting;

import java.awt.Graphics;
import java.awt.Rectangle;
import java.awt.geom.Dimension2D;
import java.awt.geom.Rectangle2D;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.Serializable;
import java.util.Objects;

import one.chartsy.charting.event.LabelRendererPropertyEvent;
import one.chartsy.charting.util.GraphicUtil;
import one.chartsy.charting.util.text.BidiUtil;

/// Represents one label-style callout anchored to a numeric value on a [Scale].
///
/// Once attached with [Scale#addAnnotation(ScaleAnnotation)] or
/// [Scale#setAnnotations(ScaleAnnotation[])], the annotation participates in the scale's bounds
/// calculation and paint pass whenever its value falls inside the axis visible range. Consumers
/// such as threshold overlays and last-price badges typically keep one instance attached and move
/// it with [#setValue(double)] instead of recreating labels during every update.
///
/// The annotation retains a mutable [LabelRenderer] by reference. Changes that affect measured
/// bounds invalidate the owning scale's layout, while drawing-only changes repaint the chart area
/// when the annotation is currently viewable. The default constructor path installs an opaque
/// renderer so standalone value badges remain legible against the plot background.
///
/// If [#getLabel()] is `null`, display text is resolved lazily from [Scale#computeLabel(double)].
/// That keeps the annotation aligned with the scale's current [ValueFormatter],
/// [StepsDefinition], and bidi settings instead of freezing a formatted string at construction
/// time.
///
/// Instances are mutable and not thread-safe.
public class ScaleAnnotation implements Serializable {

    /// Listens to the retained [LabelRenderer] and forwards meaningful presentation changes to the
    /// owning scale.
    ///
    /// Size-affecting changes invalidate scale layout because annotation bounds may move or grow.
    /// Pure drawing changes repaint only the current chart area when the annotation is attached to a
    /// viewable scale.
    private final class LabelRendererChangeListener implements PropertyChangeListener, Serializable {

        /// Applies renderer-driven repaint or relayout work for this annotation.
        @Override
        public void propertyChange(PropertyChangeEvent event) {
            if (scale == null || !scale.isViewable())
                return;
            if (event instanceof LabelRendererPropertyEvent rendererEvent) {
                if (rendererEvent.affectsSizes()) {
                    scale.invalidateLayout();
                } else if (rendererEvent.affectsDrawing()) {
                    Chart chart = scale.getChart();
                    if (chart != null)
                        chart.getChartArea().repaint();
                }
            }
        }
    }

    private double value;
    private Scale scale;
    private String label;
    private final LabelRenderer labelRenderer;
    private final PropertyChangeListener labelRendererChangeListener;

    /// Creates an annotation whose text is generated by the owning scale.
    ///
    /// This constructor uses the default opaque [LabelRenderer] configuration so the annotation
    /// paints as a filled badge once it is attached.
    ///
    /// @param value axis value to annotate
    public ScaleAnnotation(double value) {
        this(value, null);
    }

    /// Creates an annotation anchored at `value`.
    ///
    /// Passing `null` for `label` keeps the text live with the owning scale's current formatter
    /// and steps definition instead of freezing a string at construction time.
    ///
    /// @param value axis value to annotate
    /// @param label explicit display label, or `null` to use [Scale#computeLabel(double)]
    public ScaleAnnotation(double value, String label) {
        this(value, label, createDefaultLabelRenderer());
    }

    /// Creates an annotation anchored at `value` with a caller-supplied renderer.
    ///
    /// The renderer is retained, not copied. Mutating it after the annotation is attached updates
    /// the owning scale through a registered property-change listener.
    ///
    /// @param value axis value to annotate
    /// @param label explicit display label, or `null` to use [Scale#computeLabel(double)]
    /// @param labelRenderer renderer to retain for measuring and painting this annotation
    /// @throws NullPointerException if `labelRenderer` is `null`
    public ScaleAnnotation(double value, String label, LabelRenderer labelRenderer) {
        labelRendererChangeListener = new LabelRendererChangeListener();
        this.labelRenderer = Objects.requireNonNull(labelRenderer, "labelRenderer");
        this.labelRenderer.addPropertyChangeListener(labelRendererChangeListener);
        this.value = value;
        this.label = label;
    }

    private static LabelRenderer createDefaultLabelRenderer() {
        LabelRenderer renderer = new LabelRenderer();
        renderer.setOpaque(true);
        return renderer;
    }

    /// Detaches the renderer listener before the annotation is discarded by its owning scale.
    void dispose() {
        labelRenderer.removePropertyChangeListener(labelRendererChangeListener);
    }

    /// Records the owning scale so layout and repaint callbacks can flow back to it.
    void setScale(Scale scale) {
        this.scale = scale;
    }

    private DoublePoint computeLabelLocation(Chart.Area chartArea, String text) {
        Scale scale = getScale();
        DoublePoint anchor = new DoublePoint();
        scale.computeValueLocation(getValue(), anchor);
        Dimension2D labelSize = labelRenderer.getSize2D(chartArea, text, false, true);
        scale.prepare();
        return GraphicUtil.computeTextLocation(anchor, scale.getAxisAngle(getValue()), scale.getLabelDistance(),
                labelSize.getWidth(), labelSize.getHeight());
    }

    private String getDisplayLabel() {
        Scale scale = getScale();
        String displayLabel = getLabel();
        if (displayLabel == null)
            displayLabel = scale.computeLabel(getValue());
        return BidiUtil.getCombinedString(displayLabel, scale.getResolvedBaseTextDirection(),
                scale.getComponentOrientation(), false);
    }

    /// Paints this annotation with its current renderer and resolved display label.
    ///
    /// [ScaleConfiguration] implementations call this during the scale paint pass after visible
    /// range filtering has already happened.
    ///
    /// @param g destination graphics
    protected void draw(Graphics g) {
        Scale scale = getScale();
        Chart chart = scale.getChart();
        Chart.Area chartArea = (chart != null) ? chart.getChartArea() : null;
        if (chartArea == null)
            return;
        String displayLabel = getDisplayLabel();
        DoublePoint labelLocation = computeLabelLocation(chartArea, displayLabel);
        labelRenderer.paintLabel(chartArea, g, displayLabel, labelLocation.xFloor(), labelLocation.yFloor());
    }

    /// Returns the current painted bounds of this annotation.
    ///
    /// The bounds are measured from the resolved display text and current [LabelRenderer] state.
    /// When the annotation is detached, this method returns an empty [Rectangle] instead of
    /// attempting to synthesize geometry without scale context.
    ///
    /// @param bounds reusable rectangle to populate, or `null` to allocate as needed
    /// @return current label bounds for the attached scale, or an empty rectangle when detached
    public Rectangle2D getBounds(Rectangle2D bounds) {
        Scale scale = getScale();
        if (scale == null)
            return new Rectangle();
        Chart chart = scale.getChart();
        Chart.Area chartArea = (chart != null) ? chart.getChartArea() : null;
        if (chartArea == null)
            return new Rectangle();
        String displayLabel = getDisplayLabel();
        DoublePoint labelLocation = computeLabelLocation(chartArea, displayLabel);
        return labelRenderer.getBounds(chartArea, labelLocation.xFloor(), labelLocation.yFloor(), displayLabel, bounds);
    }

    /// Returns the explicit label text, if one has been set.
    ///
    /// A `null` result means the annotation currently delegates text generation to its owning
    /// scale.
    ///
    /// @return explicit label text, or `null` to follow [Scale#computeLabel(double)]
    public String getLabel() {
        return label;
    }

    /// Returns the live renderer used to measure and paint this annotation.
    ///
    /// The renderer instance is retained by reference. Mutating it while this annotation is
    /// attached updates the owning scale through the registered property-change listener.
    ///
    /// @return retained renderer for this annotation
    public LabelRenderer getLabelRenderer() {
        return labelRenderer;
    }

    /// Returns the scale this annotation is currently attached to.
    ///
    /// @return owning scale, or `null` when detached
    public final Scale getScale() {
        return scale;
    }

    /// Returns the axis value currently annotated by this instance.
    ///
    /// @return annotated axis value
    public final double getValue() {
        return value;
    }

    /// Replaces the explicit label text for this annotation.
    ///
    /// Passing `null` switches the annotation back to the scale-generated label for the current
    /// value. When the annotation is attached to a viewable scale, changing the label invalidates
    /// layout because the occupied bounds may change.
    ///
    /// @param label explicit display label, or `null` to use [Scale#computeLabel(double)]
    public void setLabel(String label) {
        if (Objects.equals(label, this.label))
            return;
        this.label = label;
        if (scale != null && scale.isViewable())
            scale.invalidateLayout();
    }

    /// Moves this annotation to a different axis value.
    ///
    /// Reusable overlays call this method instead of removing and recreating annotations. Changing
    /// the value invalidates layout on a viewable scale because both the label position and any
    /// scale-generated fallback text may change.
    ///
    /// @param value new axis value to annotate
    public void setValue(double value) {
        if (value == this.value)
            return;
        this.value = value;
        if (scale != null && scale.isViewable())
            scale.invalidateLayout();
    }
}
